### ISSUE TITLE
'drain' event is not being emitted, hanging process

### ISSUE THREAD

**Issue by chrisgladd** [cowboy/node-exit#4] opened 2013-11-25 07:46 UTC
The only place I've run into this issue is in a grunt (0.4.2) task running on my TeamCity server (a windows machine) so it may have something to do with the process.on('exit') fix not being called.

From what I can gather about the 'drain' event, I don't believe it's fired unless the stream has broken the stream._writableState.highWaterMark. So if the stream.bufferLength is not zero, but the highWaterMark hasn't been crossed, the 'drain' event will not be emitted and the process will never exit. 

`if (stream.bufferSize === 0) {`
with
`if (!stream._writableState.needDrain) {`

Seems to solve the issue for me and still preserve the task output but I'm not sure that's 100% correct either.

**Comment by EvgenyGusev** [comment] 2013-11-25 12:07
+1 
I have the same problem. In Teamcity grunt tasks not exit properly (hanging). I tried to change to 

```
if (!stream._writableState.needDrain) { 
```

and it worked!

**Comment by cowboy** [comment] 2013-11-25 12:52
I'd love for someone who knows more about Node.js streams than me to take a look at this as well. /cc @shama @vladikoff @tbranyen you guys have any opinions on this?

**Comment by Bartvds** [comment] 2013-11-25 14:07
I have a vague problem with hanging processes on Windows that I can solve with the same change to `node-exit` as @chrisgladd and @EvgenyGusev mentioned:

```
if (!stream._writableState.needDrain) {
```

I can 100% reproduce mine using local `grunt-contrib-connect`, but it only happens if I run `grunt.cmd` from grunt `v0.4.2` as `External Tool` from WebStorm (JetBrains IntelliJ). Using my regular console or WebStorm's interactive Terminal all exit as expected. Using grunt `v0.4.1` this does not hang either (but then we have the truncated output).

If I take the hanging version, go in the dependencies and change the `node-exit` line it exits as expected.

Original ticket: https://github.com/gruntjs/grunt-contrib-connect/issues/59 (with isolated demo from earlier)

**Comment by alimfeld** [comment] 2013-11-25 14:32
After upgrading to grunt 0.4.2 (with node-exit), time-grunt (https://github.com/sindresorhus/time-grunt) stops printing elapsed times. It seems like the function to print the statistics (registered on process 'exit') is not called anymore.

Also I get hanging node processes on Windows when calling grunt via the exec-maven plugin (http://mojo.codehaus.org/exec-maven-plugin/).

**Comment by cowboy** [comment] 2013-11-25 16:26
@alimfeld can you check and see if the `if (!stream._writableState.needDrain) {` fix solves your problem?

**Comment by cowboy** [comment] 2013-11-25 16:32
I'd love to fix this issue, but I need a PR for it that has been tested in Windows 7 and Windows 8, in cmd.exe, PowerShell and git-bash. I don't have access to all these combinations here, so I'm going to need some help.

Can anyone help with this?

**Comment by vladikoff** [comment] 2013-11-25 16:34
@Bartvds so you mentioned a fix worked for you, could you test out `time-grunt` and `grunt-karma` (with a redirect command `>` )

**Comment by Bartvds** [comment] 2013-11-25 17:10
@vladikoff  Sure, but it will take a moment to get a setup. I will get back with this asap.

**Comment by vladikoff** [comment] 2013-11-25 17:26
@Bartvds thanks so much!

**Comment by Bartvds** [comment] 2013-11-25 18:11
@vladikoff  Things are getting weirder by the minute:

`time-grunt` gives me no summaries on grunt `0.4.2` at all. Not even in plain `cmd.exe` console. On `0.4.1` it does. (I'm on Widows Vista 64 atm)

Neither does it when changing the line in `node-exit`.

My test code: https://github.com/Bartvds/demo-time-grunt-broken

This already breaks before I try redirecting.

---

Also I tried my earlier issue with `grunt-contrib-connect` from standard `cmd.exe` but with `>` redirect (to a file): and then it does exit as expected.

I'm no expert in CLI tricks like redirects, so what I did was just this (please confirm this is correct):

```
$ grunt test>foo.txt
```

It will run with no CLI output, exit and in `foo.txt` I will see the expected output.

---

Side info: from way back before `node-exit`, to run grunt (with the truncated output problems) as External Tool in WebStorm I also used some 'redirect-to-file-then-read-that-to-console' command to make grunt not truncate (took that from google somewhere):

```
grunt.cmd > %TEMP%\test & type %TEMP%\test & del %TEMP%\test
```

I mention this as maybe it sheds some light on what is going on (it is beyond me)

**Comment by Bartvds** [comment] 2013-11-25 18:13
In my last message I forgot to note this confirms @alimfeld 's report.

**Comment by alimfeld** [comment] 2013-11-25 19:19
It seems to be the following line in node-exit that causes time-grunt to not output the statistics anymore:

```
    // Prevent further writing.
    stream.write = function() {};
```

I guess this breaks all functions that try to write something in a process 'exit' callback (e.g. time-grunt).

@cowboy I will check tomorrow (when I have access to my Windows machine), whether the  `if (!stream._writableState.needDrain) {` fix solves the problem with hanging process and truncated output.

**Comment by Bartvds** [comment] 2013-11-25 21:03
@vladikoff I have a demo set for `grunt-karma` [here](https://github.com/Bartvds/demo-grunt-karma-hang)

Used on standard console it exits as expected on for grunt `0.4.1` and `0.4.2`.

But hangs on _both_ when redirecting `$ grunt test>foo.txt`

I tried the possible fix but is was no good. :cry:

---

(time for the customary referral to the origin of all this fun: https://github.com/joyent/node/issues/3584) :disappointed:

**Comment by cowboy** [comment] 2013-11-25 21:20
@Bartvds are you saying that the grunt-karma bug you're testing wasn't introduced in Grunt 0.4.2?

**Comment by Bartvds** [comment] 2013-11-25 21:34
@cowboy I can only say it _seems_ like that is the case. 

But I would like some confirmation on this before you build on it: this was not my original bug: maybe @stephen-styrchak-hbo who reported the `grunt-karma` [issue](https://github.com/gruntjs/grunt/issues/993) can verify this. 

(if it works for him I'm curious what the differences with my minimal demo would be)

**Comment by Bartvds** [comment] 2013-11-25 21:57
@cowboy I stripped down my demo even further, now it actually _does_ exit in grunt `0.4.1` when I redirect using `$ grunt test>foo.txt`.

**Comment by vladikoff** [comment] 2013-11-25 23:53
`if (!stream._writableState.needDrain) {` doesn't work for me in `cmd.exe`
It writes to file, full output, but hangs.

Works in PowerShell

**Comment by chrisgladd** [comment] 2013-11-26 00:40
I've added a pull request for this issue that writes an empty string to the stream and uses the callback to call `tryToExit()`. I tested it in Windows 7 & 8 in cmd, powershell, and git-bash as well as in the original issue w/ on my TeamCity server and it was functioning as expected in each case. It isn't pretty but seems to get the job done.

**Comment by vladikoff** [comment] 2013-11-26 01:03
Hey @chrisgladd , testing it out. Will let you know how it goes

**Comment by Bartvds** [comment] 2013-11-26 01:16
@chrisgladd I've tested this for my cases (Windows Vista 64): 

`node-exit`'s own tests in the `drain-fix` branch all pass.

The fix solved my original `grunt-contrib-connect` issue (grunt now exits as expected in embedded WebStorm External Tool).

The last `grunt-karma` test also exits as expected when using `$grunt test>foo.txt` (in `cmd.exe`).

Only thing remaining broken is `time-grunt`: I still get no report (but if I have to choose I'd rather have properly exiting processes then timing reports :)

**Comment by vladikoff** [comment] 2013-11-26 01:18
The fix also works for me in cmd and powershell. 

@Bartvds I noticed time-grunt uses `process.exit`, it might need to be fixed in `time-grunt` itself. 

// cc @cowboy @sindresorhus

**Comment by vladikoff** [comment] 2013-11-26 01:30
I think we also know that using `process.exit` **alone** will never work with output redirection on Windows.

**Comment by sindresorhus** [comment] 2013-11-26 08:24
@vladikoff how do you suggest I do that?

I'm just using the Node process exit event:

> Emitted when the process is about to exit. This is a good hook to perform constant time checks of the module's state (like for unit tests). The main event loop will no longer be run after the 'exit' callback finishes, so timers may not be scheduled.

**Comment by alimfeld** [comment] 2013-11-26 08:28
Trying to summarize I think we have three issues we're discussing here:
1. Hanging process on Windows when redirecting (bug in `node-exit`)
2. Truncated output (that's actually what `node-exit` tries to solve)
3. Writes are prevented after using `exit` causing e.g. `time-grunt` to not work anymore (bug/feature?)

Back on my Windows (7) machine I tried the following (in PowerShell, cmd and git bash):
- `if (!stream._writableState.needDrain) {`: Fixes 1 (but not 2 & 3)
- https://github.com/cowboy/node-exit/issues/5: Fixes 1 & 2 (but not 3)
- https://github.com/alimfeld/node-exit/commit/42c89146f5b56d3cf215a77bc65de5b7884c1a58 (basically the PR from @chrisgladd but without preventing further writes): Fixes 1, 2 & 3

However, as stated above I'm not sure, whether preventing further writes is actually a bug or a feature...

**Comment by alimfeld** [comment] 2013-11-26 08:34
I added a pull request modifying #5 to not prevent further writing: #6.

**Comment by vladikoff** [comment] 2013-11-26 08:35
@alimfeld does output redirection work for you with your changes?

**Comment by alimfeld** [comment] 2013-11-26 08:42
@vladikoff Output redirection works. However, I don't get the output written by time-grunt in the process exit callback. So I basically get all that's written up until the call to exit (i.e. all output from Grunt and Grunt tasks).

**Comment by vladikoff** [comment] 2013-11-26 08:46
Results with @alimfeld patch:
PowerShell:
![image](https://f.cloud.github.com/assets/128755/1620413/faae7ae8-5676-11e3-83fa-b7f5551ee2c5.png)

File Contents:

```
[4mRunning "jshint:all" (jshint) task[24m
[31m>> [39m0 files linted. Please check your ignored files.

[32mDone, without errors.[39m
```

---

cmd.exe:
![image](https://f.cloud.github.com/assets/128755/1620429/354667a6-5677-11e3-89d4-6749c9d515e4.png)

File Contents:

```
[4mRunning "jshint:all" (jshint) task[24m
[31m>> [39m0 files linted. Please check your ignored files.

[32mDone, without errors.[39m

[4mElapsed time[24m
jshint:all  15ms  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100%
Total 15ms
```

**Comment by vladikoff** [comment] 2013-11-26 08:48
Same results for `grunt-karma`.

So PowerShell with redirection doesn't get `process.exit` output. If that is fixed we might be good to go.

**Comment by cowboy** [comment] 2013-11-26 19:13
There are 2 problems here.
1. Grunt process hangs on Windows
2. `process.on('exit', fn)` not working - sindresorhus/time-grunt#15

Let's use this issue to fix number 1, and fix number 2 in issue #7.

**Comment by cowboy** [comment] 2013-11-26 19:26
Closed in 8b9b539bae31a49442361ae3f69a8be15f44882e.

**Comment by cowboy** [comment] 2013-11-26 19:26
v0.1.2 in npm, please test ASAP!

**Closed as completed by cowboy** 2013-11-26 19:26 UTC

**Comment by Bartvds** [comment] 2013-11-26 21:32
@cowboy I confirm node-exit v0.1.2 solved my main issues:
- the `grunt-contrib-connect` exits as expected (both via shell `>` redirect as in External Tool in WebStorm)
- the `grunt-karma` tests exits as expected too.
- `time-grunt` is still a no-show but I see you moved that to separate issue so that's cool.

Thanks for the progress so far! Epic bughunt!

**Comment by chrisgladd** [comment] 2013-11-27 00:30
Tested locally and with TeamCity issue, looks good. Thanks!

**Comment by EvgenyGusev** [comment] 2013-11-27 13:56
My TeamCity issue has gone, everything works like a charm. Thanks, guys!
